# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupomuscular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('grupomuscular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupomuscular.Grupomuscular')),
            ],
        ),
    ]
